### ISSUE TITLE
Important: repository settings

### ISSUE THREAD

**Issue by majakudlicka** [benedictrobb/BEEVR#20]
We just realised that Eoin (senior dev) is not able to merge our pull requests because he is currently not a collaborator of this repository on Github.
He suggested that you re-assign the ownership of the repository to one of us to handle admin like that. (Settings--> scroll to the bottom of the page to 'Danger Zone'-->Transfer ownership). We can re-assign the ownership back to you once we're finished developing.
Alternatively, you can add Eoin McCarthy as a collaborator yourself and we'll continue to ask you to do little admin tasks like that as they arise.

**Comment by antoniotrkdz** [comment]
Hi Ben, please do this as soon as possible as it is blocking any further work.
Expeciallly relevant for issue #13, which will enable you to see the development as it happens.
